# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_testarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testarticle',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='testarticle',
            name='created',
        ),
    ]
