# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20160321_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeOfTeachingAffairs', models.IntegerField()),
                ('personnelDivision', models.IntegerField()),
                ('schoolOfComputing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsUrl', models.URLField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('tel', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='concerndirection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concernDirection', to='snippets.User'),
        ),
    ]
