# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20160409_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
