# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_schoolnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolNews',
        ),
    ]
