# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openlock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagestore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagePath', models.CharField(blank=True, default='/images/', max_length=250)),
                ('imageName', models.CharField(blank=True, default='unknow.jpg', max_length=100)),
            ],
        ),
    ]
