# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openlock', '0002_imagestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('userpwd', models.CharField(max_length=100)),
            ],
        ),
    ]
