# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobook', '0002_auto_20160711_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='stateProvince',
            new_name='state_province',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publicationDate',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
